# Generated by Django 4.0.3 on 2022-04-21 22:15

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_profile_picture', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dbgbail9r/image/upload/v1650578825/karakana/user-authentication/user_profile_image.jpg', max_length=255, verbose_name='karakana/assets/')),
                ('customer_bio', models.TextField(blank=True, max_length=50)),
                ('customer_phone_number', models.CharField(blank=True, max_length=17, null=True)),
                ('customer_location', models.CharField(blank=True, max_length=25, null=True)),
                ('customer_since', models.DateField(default=django.utils.timezone.now)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
